import fs from 'fs';
import path from 'path';

console.log('Running Production Smoke Verification...');

const outDir = path.join(process.cwd(), '.next/server/app');
const projectsDataPath = path.join(process.cwd(), 'src/data/projects.ts');
const credentialsDataPath = path.join(process.cwd(), 'src/data/credentials.ts');
const contentDataPath = path.join(process.cwd(), 'src/data/content.ts');
const resumeSourcePath = path.join(process.cwd(), 'resume/resume.html');
const resumePdfPath = path.join(process.cwd(), 'public/victor-resume.pdf');
const nextConfigPath = path.join(process.cwd(), 'next.config.ts');
const agentsPath = path.join(process.cwd(), 'AGENTS.md');

// 1. Verify Homepage
const homeHtmlPath = path.join(outDir, 'index.html');
if (!fs.existsSync(homeHtmlPath)) {
  console.error('FAIL: Homepage build output index.html not found');
  process.exit(1);
}

const homeHtml = fs.readFileSync(homeHtmlPath, 'utf-8');

if (!homeHtml.includes('VICTOR')) {
  console.error('FAIL: Hero text VICTOR not found on homepage');
  process.exit(1);
}

if (!homeHtml.includes('AI Automation &amp; Agent Workflow Builder')) {
  console.error('FAIL: Homepage missing approved Builder positioning');
  process.exit(1);
}

if (homeHtml.includes('Bachelor of Applied Science, Industrial Chemistry')) {
  console.error('FAIL: Homepage contains an uncompleted degree as a completed Bachelor credential');
  process.exit(1);
}

// 2. Privacy & Exclusions Check
if (homeHtml.includes('Ye Man')) {
  console.error('FAIL: Confidential client Ye Man found on homepage');
  process.exit(1);
}

for (const requiredPath of [contentDataPath, resumeSourcePath, resumePdfPath, nextConfigPath, agentsPath]) {
  if (!fs.existsSync(requiredPath)) {
    console.error(`FAIL: Required public profile artifact not found at ${requiredPath}`);
    process.exit(1);
  }
}

const contentSource = fs.readFileSync(contentDataPath, 'utf-8');
const resumeSource = fs.readFileSync(resumeSourcePath, 'utf-8');
const resumePdf = fs.readFileSync(resumePdfPath, 'latin1');
const nextConfigSource = fs.readFileSync(nextConfigPath, 'utf-8');
const agentsSource = fs.readFileSync(agentsPath, 'utf-8');

if (!/agentRules:\s*false/.test(nextConfigSource)) {
  console.error('FAIL: Next.js agentRules must stay disabled to protect the reviewed AGENTS.md');
  process.exit(1);
}

if (agentsSource.includes('BEGIN:nextjs-agent-rules')) {
  console.error('FAIL: AGENTS.md contains an autogenerated Next.js instruction block');
  process.exit(1);
}

for (const [label, source] of [['portfolio content', contentSource], ['resume source', resumeSource]]) {
  if (source.includes('Bachelor of Applied Science, Industrial Chemistry')) {
    console.error(`FAIL: ${label} represents unfinished study as a completed Bachelor degree`);
    process.exit(1);
  }
}

if (!resumeSource.includes('degree not completed')) {
  console.error('FAIL: Resume must state clearly that the Industrial Chemistry degree was not completed');
  process.exit(1);
}

for (const link of [
  ['LinkedIn', 'https://www.linkedin.com/in/aung-hein-kyaw'],
  ['GitHub', 'https://github.com/ahk1542001-wq'],
  ['Portfolio', 'https://portfolioweb-three-sigma.vercel.app'],
]) {
  const [label, href] = link;
  if (!resumeSource.includes(`href="${href}"`) || !resumeSource.includes(`>${label}<`)) {
    console.error(`FAIL: Resume missing named clickable ${label} link`);
    process.exit(1);
  }
}

if (!resumePdf.startsWith('%PDF-')) {
  console.error('FAIL: victor-resume.pdf is not a valid PDF header');
  process.exit(1);
}

const pdfPageCount = (resumePdf.match(/\/Type\s*\/Page(?!s)\b/g) || []).length;
if (pdfPageCount !== 2) {
  console.error(`FAIL: Resume must be exactly 2 pages, found ${pdfPageCount}`);
  process.exit(1);
}

// 3. Dynamically extract project IDs from projects.ts to prevent silent omissions
if (!fs.existsSync(projectsDataPath)) {
  console.error(`FAIL: Projects data source not found at ${projectsDataPath}`);
  process.exit(1);
}

const projectsSource = fs.readFileSync(projectsDataPath, 'utf-8');
const idMatches = [...projectsSource.matchAll(/id:\s*['"]([^'"]+)['"]/g)];
const projectSlugs = idMatches.map((m) => m[1]);

if (projectSlugs.length < 10) {
  console.error(`FAIL: Expected at least 10 projects, but found ${projectSlugs.length}`);
  process.exit(1);
}

console.log(`Verifying ${projectSlugs.length} project case studies...`);

// 4. Verify Each Project Route & Mandatory Sections
const mandatorySections = [
  'The Problem',
  'My Role',
  'What I Personally Directed',
  'The Solution',
  'Verified Outcome'
];

for (const slug of projectSlugs) {
  // Check link existence on homepage
  if (!homeHtml.includes(`/projects/${slug}`)) {
    console.error(`FAIL: Homepage missing link to project ${slug}`);
    process.exit(1);
  }

  const projectHtmlPath = path.join(outDir, 'projects', `${slug}.html`);
  if (!fs.existsSync(projectHtmlPath)) {
    console.error(`FAIL: Case study page for ${slug} not found at ${projectHtmlPath}`);
    process.exit(1);
  }

  const projectHtml = fs.readFileSync(projectHtmlPath, 'utf-8');
  for (const section of mandatorySections) {
    if (!projectHtml.includes(section)) {
      console.error(`FAIL: ${slug} missing mandatory case study section "${section}"`);
      process.exit(1);
    }
  }
}

// 5. Specific Verification for Hackathon & Architecture Showcases
const gcpHtml = fs.readFileSync(path.join(outDir, 'projects', 'gcp-genai-agent-architectures.html'), 'utf-8');
if (!gcpHtml.includes('https://youtu.be/boDhNKUwZyE')) {
  console.error('FAIL: GCP GenAI Agent Architectures missing YouTube demo link');
  process.exit(1);
}
if (!homeHtml.includes('boDhNKUwZyE')) {
  console.error('FAIL: Homepage missing GCP GenAI Agent Architectures YouTube thumbnail');
  process.exit(1);
}

const fyfHtml = fs.readFileSync(path.join(outDir, 'projects', 'fyf-video-pipeline.html'), 'utf-8');
if (!fyfHtml.includes('https://youtu.be/9MYzaFjR0ck')) {
  console.error('FAIL: FYF Video Pipeline missing YouTube demo link');
  process.exit(1);
}

const travelCareHtml = fs.readFileSync(path.join(outDir, 'projects', 'travelcare-ai.html'), 'utf-8');
if (!travelCareHtml.includes('https://youtu.be/H-MC2JHWl7M')) {
  console.error('FAIL: TravelCare AI missing YouTube demo link');
  process.exit(1);
}
if (!travelCareHtml.includes('https://github.com/ahk1542001-wq/alibaba-atlas-rescue-agent')) {
  console.error('FAIL: TravelCare AI missing GitHub repository link');
  process.exit(1);
}

// 6. Verify Dedicated Credentials Page
if (!homeHtml.includes('/credentials')) {
  console.error('FAIL: Homepage missing link to /credentials');
  process.exit(1);
}

const credentialsHtmlPath = path.join(outDir, 'credentials.html');
if (!fs.existsSync(credentialsHtmlPath)) {
  console.error('FAIL: Credentials build output credentials.html not found');
  process.exit(1);
}

const credentialsHtml = fs.readFileSync(credentialsHtmlPath, 'utf-8');
if (!credentialsHtml.includes('Verified AI Credentials')) {
  console.error('FAIL: Credentials page missing heading "Verified AI Credentials"');
  process.exit(1);
}
if (!fs.existsSync(credentialsDataPath)) {
  console.error(`FAIL: Credentials data source not found at ${credentialsDataPath}`);
  process.exit(1);
}

const credentialsSource = fs.readFileSync(credentialsDataPath, 'utf-8');
const verifyUrlMatches = [...credentialsSource.matchAll(/verifyUrl:\s*['"]([^'"]+)['"]/g)];
const verifyUrls = verifyUrlMatches.map((m) => m[1]);

if (verifyUrls.length < 11) {
  console.error(`FAIL: Expected at least 11 verifiable credentials in credentials.ts, found ${verifyUrls.length}`);
  process.exit(1);
}

const requiredSkilljarUrls = [
  'https://verify.skilljar.com/c/pjy6v36xapxe',
  'https://verify.skilljar.com/c/n83j7p93x9fg',
  'https://verify.skilljar.com/c/a2ynyb62bxr6',
  'https://verify.skilljar.com/c/eofti5gaf6xd',
  'https://verify.skilljar.com/c/wdk2aonf9a73',
  'https://verify.skilljar.com/c/kczxajmkb28k',
];

for (const skilljarUrl of requiredSkilljarUrls) {
  if (!verifyUrls.includes(skilljarUrl)) {
    console.error(`FAIL: Missing required Skilljar URL in credentials.ts: ${skilljarUrl}`);
    process.exit(1);
  }
}

for (const url of verifyUrls) {
  if (!credentialsHtml.includes(url)) {
    console.error(`FAIL: Credentials page missing verification URL: ${url}`);
    process.exit(1);
  }
}

console.log(`PASS: All production smoke checks (${projectSlugs.length} projects + credentials page + homepage links + mandatory sections) completed successfully!`);
